export const locations = [
  {
    bingo_value: 1,
    name: "Escuela Nº 337 General Belgrano",
    img: "1.jpg",
    province: "Catamarca",
    texto: "Belén, Catamarca",
  },
  {
    bingo_value: 2,
    name: "Escuela Nº 252",
    img: "2.jpg",
    province: "Catamarca",
    texto: "las Mojarras, Catamarca",
  },
  {
    bingo_value: 3,
    name: "Escuela Nº 241",
    img: "3.jpg",
    province: "Catamarca",
    texto: "Fuerte Quemado, Catamarca",
  },
  {
    bingo_value: 4,
    name: "Escuela Nº 288 Presidente J.D. Perón",
    img: "4.jpg",
    province: "Catamarca",
    texto: "Hualfin, Catamarca",
  },
  {
    bingo_value: 5,
    name: "Escuela Nº 363",
    img: "5.jpg",
    province: "Catamarca",
    texto: "El Puesto, Catamarca",
  },
  {
    bingo_value: 6,
    name: "Escuela Nº 72 Constancio C. Vigil",

    img: "6.jpg",
    province: "Chubut",
    texto: "Río Mayo, Chubut",
  },
  {
    bingo_value: 7,
    name: "Escuela Nº 148 25 de Mayo",
    img: "7.jpg",
    province: "Chubut",
    texto: "Río Mayo, Chubut",
  },
  {
    bingo_value: 8,
    name: "Escuela Nº 36 Luisa Irene Accomazo de González ",
    img: "8.jpg",
    province: "Chubut",
    texto: "Río Mayo, Chubut",
  },
  {
    bingo_value: 9,
    name: "Escuela Nº 93",
    img: "9.jpg",
    province: "Jujuy",
    texto: "Huachichocana, Jujuy",
  },
  {
    bingo_value: 10,
    name: "Escuela Nº 373",
    img: "10.jpg",
    province: "Jujuy",
    texto: "Puerta de Lipan, Jujuy",
  },
  {
    bingo_value: 11,
    name: "Escuela Nº 21 Pedro Goyena",
    img: "11.jpg",
    province: "Jujuy",
    texto: "Purmamarca, Jujuy",
  },
  {
    bingo_value: 12,
    name: "Escuela Nº 308 Provincia de San Juan",
    img: "12.jpg",
    province: "Jujuy ",
    texto: "Turnalito, Jujuy",
  },
  {
    bingo_value: 13,
    name: "Escuela Nº 53 Dr Marcelino Vargas ",
    img: "13.jpg",
    province: "Jujuy",
    texto: "Purmamarca, Jujuy",
  },
  {
    bingo_value: 14,
    name: "Escuela Nº 24 Provincia de Neuquén",
    img: "14.jpg",
    province: "La Rioja",
    texto: "Salicas, La Rioja",
  },
  {
    bingo_value: 15,
    name: "Escuela Nº 63 Mtro. Guillermo Ríos",
    img: "15.jpg",
    province: "La Rioja",
    texto: "Suriyaco, La Rioja",
  },
  {
    bingo_value: 16,
    name: "Escuela Nº 142 Maestro Guillermo Sotomayor",

    img: "16.jpg",
    province: "La Rioja",
    texto: "Tuyubil, La Rioja",
  },
  {
    bingo_value: 17,
    name: "Escuela Nº 62 Soberanía Argentina",
    img: "17.jpg",
    province: "La Rioja",
    texto: "Los Robles, La Rioja",
  },
  {
    bingo_value: 18,
    name: "Escuela Nº 118 El Retiro",
    img: "18.jpg",
    province: "La Rioja ",
    texto: "Alpasinche, La Rioja",
  },
  {
    bingo_value: 19,
    name: "Escuela Nº 44 Filomena Navarro de Góndolo",
    img: "19.jpg",
    province: "La Rioja",
    texto: "Chaupihuasi, La Rioja",
  },
  {
    bingo_value: 20,
    name: "Escuela Nº 277 Flaviano de la Colina ",
    img: "20.jpg",
    province: "La Rioja",
    texto: "Shaqui, La Rioja",
  },
  {
    bingo_value: 21,
    name: "Escuela Nº 1364 Dr José Ceferino Palma",

    img: "21.jpg",
    province: "Mendoza",
    texto: "Estancia las Cuevas, Mendoza",
  },
  {
    bingo_value: 22,
    name: "Escuela Nº 1528 Ricardo Palma",
    img: "22.jpg",
    province: "Mendoza",
    texto: "La Carrera, Mendoza",
  },
  {
    bingo_value: 23,
    name: "Escuela Nº 1555 Lucila Barrionuevo de Bombal",
    img: "23.jpg",
    province: "Mendoza",
    texto: "Ancon, Mendoza",
  },
  {
    bingo_value: 24,
    name: "Escuela Nº 1518 Domingo Lucas Bombal",
    img: "24.jpg",
    province: "Mendoza",
    texto: "San José, Mendoza",
  },
  {
    bingo_value: 25,
    name: "Escuela Nº 1066 Juan Bautista Alberdi",
    img: "25.jpg",
    province: "Mendoza",
    texto: "El Peral, Mendoza",
  },
  {
    bingo_value: 26,
    name: "Escuela Nº 1451 Alberto Gino Mario Greco",

    img: "26.jpg",
    province: "Mendoza",
    texto: "Santa Clara, Mendoza",
  },
  {
    bingo_value: 27,
    name: "Escuela Nº 1564 Juan González Ozo",
    img: "27.jpg",
    province: "Mendoza",
    texto: "Ojo de Agua, Mendoza",
  },
  {
    bingo_value: 28,
    name: "Escuela Nº 1521 Hermenegildo Hidalgo",
    img: "28.jpg",
    province: "Mendoza",
    texto: "Gualtallary, Mendoza",
  },
  {
    bingo_value: 29,
    name: "Escuela Sec Nº 4060 Dr Ernesto Piaggi",
    img: "29.jpg",
    province: "Mendoza",
    texto: "Gualtallary, Mendoza",
  },
  {
    bingo_value: 30,
    name: "Escuela Nº 75 Enrique Cheuquel",
    img: "30.jpg",
    province: "Neuquén",
    texto: "Paraje Mallin de los Caballos, Neuquén",
  },
  {
    bingo_value: 31,
    name: "Escuela Nº 85 Soberanía Argentina",
    img: "31.jpg",

    province: "Neuquén",
    texto: "Paraje los Hornos de Covunco, Neuquén",
  },
  {
    bingo_value: 32,
    name: "Escuela Nº 283 Emma Cárcamo",
    img: "32.jpg",
    province: "Neuquén",
    texto: "San Demetrio Las Lajas, Neuquén",
  },
  {
    bingo_value: 33,
    name: "Escuela Nº 128",
    img: "33.jpg",
    province: "Neuquén",
    texto: "Villa de Agrio, Neuquén",
  },
  {
    bingo_value: 34,
    name: "Escuela Nº 279",
    img: "34.jpg",
    province: "Neuquén",
    texto: "Las Lajas, Neuquén",
  },
  {
    bingo_value: 35,
    name: "Escuela Nº 224",
    img: "35.jpg",
    province: "Neuquén",
    texto: "Bajada Vieja, Neuquén",
  },
  {
    bingo_value: 36,
    name: "Escuela Nº 122 Juan Lavalle",
    img: "36.jpg",

    province: "Río Negro",
    texto: "Villa Manzano, Río Negro",
  },
  {
    bingo_value: 37,
    name: "Escuela Nº 373 Villa Manzano",
    img: "37.jpg",
    province: "Río Negro",
    texto: "Villa Manzano, Río Negro",
  },
  {
    bingo_value: 38,
    name: "Escuela Nº 191",
    img: "38.jpg",
    province: "Río Negro",
    texto: "Sargento Vidal, Río Negro",
  },
  {
    bingo_value: 39,
    name: "Escuela Nº 300",
    img: "39.jpg",
    province: "Río Negro",
    texto: "San Isidro, Río Negro",
  },
  {
    bingo_value: 40,
    name: "Escuela Nº 152 3era D",
    img: "40.jpg",
    province: "Río Negro ",
    texto: "Cerro Alto, Río Negro",
  },
  {
    bingo_value: 41,
    name: "Escuela Nº 158 San Ignacio de Loyola",
    img: "41.jpg",

    province: "Río Negro",
    texto: "Corralito, Río Negro",
  },
  {
    bingo_value: 42,
    name: "Escuela Nº 65 Lonko Lucerinta Cañum",
    img: "42.jpg",
    province: "Río Negro",
    texto: "Paraje Chacay Huarruca, Río Negro",
  },
  {
    bingo_value: 43,
    name: "Escuela Nº 269 Cardenal Cagliero",
    img: "43.jpg",
    province: "Río Negro",
    texto: "Pilcaniyeu, Río Negro",
  },
  {
    bingo_value: 44,
    name: "Escuela Nº 245 2da D",
    img: "44.jpg",
    province: "Río Negro",
    texto: "Villa Llanquin, Río Negro",
  },
  {
    bingo_value: 45,
    name: "Escuela Nº 231",
    img: "45.jpg",
    province: "Río Negro",
    texto: "Pichu Leufu, Río Negro",
  },
  {
    bingo_value: 46,
    name: "Escuela Nº 98",
    img: "46.jpg",

    province: "Río Negro",
    texto: "Pichu Leufu abajo, Río Negro",
  },
  {
    bingo_value: 47,
    name: "Escuela Nº 4388 Maria Mercedes Peñaloza",
    img: "47.jpg",
    province: "Salta",
    texto: "Santa Rosa, Salta",
  },
  {
    bingo_value: 48,
    name: "Escuela Nº 4387 Pastorcito de Fátima",
    img: "48.jpg",
    province: "Salta",
    texto: "Salta",
  },
  {
    bingo_value: 49,
    name: "Escuela Nº 4381 Nevado de Acay",
    img: "49.jpg",
    province: "Salta",
    texto: "La Poma, Salta",
  },
  {
    bingo_value: 50,
    name: "Escuela Nº 4396 José Hernández",
    img: "50.jpg",
    province: "Salta",
    texto: "El Trigal, Salta",
  },
  {
    bingo_value: 51,
    name: "Escuela Nº 4244 El Nevado de Cachi",
    img: "51.jpg",

    province: "Salta",
    texto: "Las Trancas, Salta",
  },
  {
    bingo_value: 52,
    name: "Escuela Nº 4105 Dr Francisco Alsina",
    img: "52.jpg",
    province: "Salta",
    texto: "San Rafael, Salta",
  },
  {
    bingo_value: 53,
    name: "Escuela Josefa Ramirez de García",
    img: "53.jpg",
    province: "San Juan",
    texto: "Pedernal, San Juan",
  },
  {
    bingo_value: 54,
    name: "Escuela Dr Albert Einstein",
    img: "54.jpg",
    province: "San Juan",
    texto: "Cañada Honda, San Juan",
  },
  {
    bingo_value: 55,
    name: "Escuela Olegario Victor Andrade",
    img: "55.jpg",
    province: "San Juan",
    texto: "Guanacache, San Juan",
  },
  {
    bingo_value: 56,
    name: "Escuela Batalla de Suipacha",
    img: "56.jpg",
    province: "San Juan",

    texto: "Retamito, Villa media Agua, San Juan",
  },
  {
    bingo_value: 57,
    name: "Escuela Profesor Alejandro Mathus",
    img: "57.jpg",
    province: "San Juan",
    texto: "Cienaguita, San Juan",
  },
  {
    bingo_value: 58,
    name: "Escuela José Lombardo Radice",
    img: "58.jpg",
    province: "San Juan",
    texto: "Divisadero, San Juan",
  },
  {
    bingo_value: 59,
    name: "Escuela Victorina L, de Navarro",
    img: "59.jpg",
    province: "San Juan",
    texto: "Media Agua, San Juan",
  },
  {
    bingo_value: 60,
    name: "Escuela Nº 16 Rudo Padre Federico Torres",
    img: "60.jpg",
    province: "Santa Cruz",
    texto: "Tres Lagos, Santa Cruz",
  },
  {
    bingo_value: 61,
    name: "Escuela Sec. de Quilmes",
    img: "61.jpg",
    province: "Tucumán",
    texto: "Quilmes, Tucumán",
  },
  {
    bingo_value: 62,
    name: "Escuela Sec. de Ampimpa",
    img: "62.jpg",
    province: "Tucumán",
    texto: "Ampimpa, Tucumán",
  },
  {
    bingo_value: 63,
    name: "Escuela Nº 33 Nuestra Señora del Carmen",
    img: "63.jpg",
    province: "Tucumán",
    texto: "El Paso, Tucumán",
  },
  {
    bingo_value: 64,
    name: "Escuela Nº 217 Angel Maria Soria",
    img: "64.jpg",
    province: "Tucumán",
    texto: "El Bañado, Tucumán",
  },
  {
    bingo_value: 65,
    name: "Escuela Nº. 23 Segundo Felino Ramos",
    img: "65.jpg",
    province: "Tucumán",
    texto: "Colalao del Valle, Tucumán",
  },
  {
    bingo_value: 66,
    name: "Escuela Nº 37 Para La Libertad",
    img: "66.jpg",
    province: "Tucumán",

    texto: "Colalao del Valle, Tucumán",
  },
  {
    bingo_value: 67,
    name: "Escuela Nº 325 24 de Septiembre",
    img: "67.jpg",
    province: "Tucumán",
    texto: "Quebrada de los Chañares, Tucumán",
  },
  {
    bingo_value: 68,
    name: "Escuela Nº 213 Cacique Martín Iquin",
    img: "68.jpg",
    province: "Tucumán",
    texto: "Quilmes, Tucumán",
  },
  {
    bingo_value: 69,
    name: "Escuela Nº 32 Dr. Alfredo Palacios",
    img: "69.jpg",
    province: "Tucumán",
    texto: "Colalao del Valle, Tucumán",
  },
  {
    bingo_value: 70,
    name: "Escuela Nº 10 Claudia Velez de Cano",
    img: "70.jpg",
    province: "Tucumán",
    texto: "Amaicha del Valle, Tucumán",
  },
  {
    bingo_value: 71,
    name: "Escuela Nº 336",
    img: "71.jpg",
    province: "Tucumán",

    texto: "Salas, Tucumán",
  },
  {
    bingo_value: 72,
    name: "Escuela Nº 340 Nuestra Señora de los Remedios",
    img: "72.jpg",
    province: "Tucumán",
    texto: "Yasyamayo, Tucumán",
  },
  {
    bingo_value: 73,
    name: "Escuela Nº 371 Juan Calchaqui",
    img: "73.jpg",
    province: "Tucumán",
    texto: "Ampimpa, Tucumán",
  },
  {
    bingo_value: 74,
    name: "Escuela Coronel José Ignacio Murga",
    img: "74.jpg",
    province: "Tucumán",
    texto: "El Carmen, Tucumán",
  },
  {
    bingo_value: 75,
    name: "Escuela Nº 50 Santa Cecilia",
    img: "75.jpg",
    province: "Tucumán",
    texto: "Los Zazos, Tucumán",
  },
  {
    bingo_value: 76,
    name: "Escuela Manuela Pedraza",
    img: "76.jpg",
    province: "Tucumán",
    texto: "Los Corpitos, Tucumán",
  },
];

// export const locations = [
//   {
//     bingo_value: 1,
//     name: "San Ignacio de Loyola",
//     img: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Buenos_Aires_Obelisk-20110509-RM-104316.jpg",
//     province: "Buenos Aires",
//     texto: "hola",
//   },
//   {
//     bingo_value: 2,
//     name: "Lonko Lucerinta Cañum",
//     img: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Mirador_al_Llao_Llao.jpg",
//     province: "Bariloche",
//     texto: "hola",
//   },
//   {
//     bingo_value: 3,
//     name: "Josefa Ramirez de García",
//     img: "https://upload.wikimedia.org/wikipedia/commons/9/95/Provincia_de_C%C3%B3rdoba%2C_Argentina.png",
//     province: "Buenos Aires",
//     texto: "hola",
//   },
//   {
//     bingo_value: 4,
//     name: "YQS",
//     img: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Buenos_Aires_Obelisk-20110509-RM-104316.jpg",
//     province: "Bariloche",
//     texto: "hola",
//   },
//   // Add the rest of your 74 locations here
// ];
