// src/provinces.js
const ZOOM = 4;
export const provinces = {
  BuenosAires: { center: { x: 60, y: 56 }, zoom: ZOOM },
  Catamarca: { center: { x: 30, y: 28 }, zoom: ZOOM },
  Chaco: { center: { x: 58, y: 19 }, zoom: ZOOM },
  Chubut: { center: { x: 22, y: 67 }, zoom: ZOOM },
  Cordoba: { center: { x: 51, y: 36 }, zoom: ZOOM },
  Corrientes: { center: { x: 65, y: 27 }, zoom: ZOOM },
  EntreRios: { center: { x: 62, y: 42 }, zoom: ZOOM },
  Formosa: { center: { x: 60, y: 11 }, zoom: ZOOM },
  Jujuy: { center: { x: 28, y: 13 }, zoom: ZOOM },
  LaPampa: { center: { x: 46, y: 56 }, zoom: ZOOM },
  LaRioja: { center: { x: 21, y: 30 }, zoom: ZOOM },
  Mendoza: { center: { x: 20, y: 42 }, zoom: ZOOM },
  Misiones: { center: { x: 70, y: 18 }, zoom: ZOOM },
  Neuquen: { center: { x: 14, y: 54 }, zoom: ZOOM },
  RioNegro: { center: { x: 22, y: 62 }, zoom: ZOOM },
  Salta: { center: { x: 39, y: 17 }, zoom: ZOOM },
  SanJuan: { center: { x: 13, y: 33 }, zoom: ZOOM },
  SanLuis: { center: { x: 44, y: 46 }, zoom: ZOOM },
  SantaCruz: { center: { x: 20, y: 84 }, zoom: ZOOM },
  SantaFe: { center: { x: 58, y: 35 }, zoom: ZOOM },
  SantiagoDelEstero: { center: { x: 50, y: 26 }, zoom: ZOOM },
  TierraDelFuego: { center: { x: 40, y: 98 }, zoom: ZOOM },
  Tucuman: { center: { x: 31, y: 23 }, zoom: ZOOM },
};
